spring.application.name=student-system

# MySQL Database Connection Settings
spring.datasource.url=jdbc:mysql://localhost:3306/StudentAdmissionDB?useSSL=false&serverTimezone=UTC
spring.datasource.username=YOUR_USERNAME
spring.datasource.password=YOUR_PASSWORD

# Spring Data JPA / Hibernate Settings
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# THE MAGIC LINE: This tells Spring to automatically create or update your database tables!
spring.jpa.hibernate.ddl-auto=update
server.port=9090